"""empty message

Revision ID: 387af7742362
Revises: 603a07342d3e
Create Date: 2024-08-15 00:00:15.536592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387af7742362'
down_revision: Union[str, None] = '603a07342d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapons', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapons', 'name')
    # ### end Alembic commands ###
