"""weapon

Revision ID: 40b30c007ca1
Revises: 0d904f63fa0c
Create Date: 2024-08-13 22:37:42.385138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b30c007ca1'
down_revision: Union[str, None] = '0d904f63fa0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lvl', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strengh', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agility', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('endurance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('atack', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_point', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_lvl', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='frog_pkey')
    )
    # ### end Alembic commands ###
